ecommerce/shopcartproject/cart/urls.py
from django.urls import path

from cart import views

app_name = 'cart'

urlpatterns = [
    path('add/<int:product_id>/', views.add_cart, name='add_cart'),
    path('cartt', views.cart_detail, name='cart_detail'),
    path('minus/<int:product_id>/', views.minus_cart, name='minus_cart'),
    path('remove/<int:product_id>/', views.full_remove, name='full_remove'),
    path('payment', views.payment, name='payment'),
    path('ordersuccessful', views.ordersuccess, name='ordersuccess'),
]

ecommerce/shopcartproject/searchapp/urls.py
from django.urls import path

from searchapp import views

app_name = 'searchapp'
urlpatterns = [
    path('searchrslt', views.searchresult, name='searchresult'),

]

ecommerce/shopcartproject/shopapp/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.urls import path

from shopapp import views

app_name = 'shopapp'
urlpatterns = [
    path('', views.allprodcat, name='allprodcat'),
    path('<slug:c_slug>/', views.allprodcat, name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/', views.prodetail, name='prodetail'),
]

ecommerce/shopcartproject/shopcartproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include ('shopapp.urls')),
    path('search/', include('searchapp.urls')),
    path('cart/', include('cart.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

ecommerce/shopcartproject/cart/models.py
from django.db import models
from shopapp.models import product

# Create your models here.
class Cart(models.Model):
    cart_id=models.CharField(max_length=250,blank=True)
    date_added=models.DateField(auto_now_add=True)
    class Meta:
        db_table='Cart'
        ordering=['date_added']
    def __str__(self):
        return '{}'.format(self.cart_id)

class CartItem(models.Model):
    product=models.ForeignKey(product,on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    active=models.BooleanField(default=True)
    class Meta:
        db_table='CartItem'
    def sub_total(self):
        return self.product.price * self.quantity
    def __str__(self):
        return '{}'.format(self.product)

ecommerce/shopcartproject/searchapp/models.py
from django.db import models

# Create your models here.

ecommerce/shopcartproject/shopapp/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class category(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    image=models.ImageField(upload_to='category',blank=True)
    class Meta:
            ordering=('name',)
            verbose_name='category'
            verbose_name_plural='categories'
    def get_url(self):
        return reverse('shopapp:products_by_category',args=[self.slug])
    def __str__(self):
        return   '{}'.format(self.name)

class product(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    category=models.ForeignKey(category,on_delete=models.CASCADE)
    image = models.ImageField(upload_to='category', blank=True)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def get_url(self):
        return reverse('shopapp:prodetail', args=[self.category.slug,self.slug])

    def __str__(self):
        return '{}'.format(self.name)

ecommerce/shopcartproject/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.exceptions import ObjectDoesNotExist
from .models import Cart,CartItem
from shopapp.models import product
# Create your views here.
def _cart_id(request):
    cart=request.session.session_key
    if not cart:
        cart=request.session.create()
    return cart
def add_cart(request,product_id):
    pproduct=product.objects.get(id=product_id)
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart=Cart.objects.create(cart_id=_cart_id(request))
        cart.save()
    try:
        cart_item=CartItem.objects.get(product=pproduct,cart=cart)
        if cart_item.quantity < cart_item.product.stock:
          cart_item.quantity += 1
        cart_item.save()
    except CartItem.DoesNotExist :
        cart_item=CartItem.objects.create(product=pproduct, quantity=1, cart=cart)
        cart_item.save()
    return redirect('cart:cart_detail')
def cart_detail(request,total=0,counter=0,cart_items=None):
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
        cart_items=CartItem.objects.filter(cart=cart,active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request,'cart.html',dict(cart_items=cart_items,total=total,counter=counter))

def minus_cart(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    pproduct=get_object_or_404(product,id=product_id)
    cart_item=CartItem.objects.get(product=pproduct,cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')
def full_remove(request, product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    Product=get_object_or_404(product,id=product_id)
    cart_item=CartItem.objects.get(cart=cart,product=Product)
    cart_item.delete()
    return redirect('cart:cart_detail')
def payment(request):
    total=0
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart, active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
    except ObjectDoesNotExist:
        pass
    return render(request,'payment.html',dict(total=total))
def ordersuccess(request):
    return render(request,'ordersuccess.html')

ecommerce/shopcartproject/searchapp/views.py
from django.db.models import Q
from django.shortcuts import render, redirect
from django.urls import reverse

from shopapp.models import product
from shopapp.views import allprodcat


# Create your views here.



def searchresult(request):
    products=None
    query=None
    if 'q' in request.GET:
        query=request.GET.get('q')
        products=product.objects.all().filter(Q(name__contains=query))
        return render(request,'search.html',{'query':query,'products':products})

ecommerce/shopcartproject/shopapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404

from shopapp.models import category,product
from django.core.paginator import Paginator,InvalidPage,EmptyPage

# Create your views here.
# def index(request):
#     return HttpResponse('hey hello')
def allprodcat(request,c_slug=None):
    c_page=None
    products_list=None
    if c_slug!=None:
        c_page=get_object_or_404(category,slug=c_slug)
        products_list=product.objects.all().filter(category=c_page,available=True)
    else:
        products_list = product.objects.all().filter( available=True)
    paginator=Paginator(products_list,6)
    try:
        page=int(request.GET.get('page','1'))
    except:
        page=1
    try:
        products=paginator.page(page)
    except(EmptyPage,InvalidPage):
        products=paginator.page(paginator.num_pages)
    return render(request,'category.html',{'category':c_page,'products':products})

def prodetail(request,c_slug,product_slug):
    try:
        Product=product.objects.get(category__slug=c_slug,slug=product_slug)
    except Exception as e:
        raise e

    return render(request,'product.html',{'product':Product})

ecommerce/shopcartproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'css/custom.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
<!--    <script src="https://kit.fontawesome.com/a076d05399.js"></script>-->
    <script src="https://kit.fontawesome.com/4f250caee7.js" crossorigin="anonymous"></script>

    <meta name="description" content="{% block metadescription %}{% endblock %}">

    <title>{% block title %}{% endblock %}</title>

</head>
<body style="font-family: 'Raleway', sans-serif;">
<div class="container">
    {% include 'header.html' %}
    {% include 'nav.html' %}
    {% block content %}
    {% endblock%}

</div>
{% include 'footer.html' %}
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

ecommerce/shopcartproject/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

This is the cart page. Proceed to review your items and place the order

{% endblock %}
{% block title %}
Cart - NOUVA tech pvt ltd

{% endblock %}
{% block content %}
{% if not cart_items %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_tittle" style="letter-spacing : .2em;font-size : 16px;text-transform : uppercase;">
            Your Cart is Empty
        </h1>
        <br>
        <a href="/" class="btn btn-danger my_button" style="margin-bottom:306px;">Add Items</a>


    </div>
</div>
{% else %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_tittle">
            Your Cart
        </h1>
        <br>
    </div>
    <div class="row mx-auto">
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
            <table class="table my_table">
                <thead class="my_thead">
                <tr>
                    <th colspan="5">
                        Your Items

                    </th>

                </tr>

                </thead>
                <tbody>
                {% for cart_item in cart_items %}
                <tr>
                    <td>
                        <a href="{{cart_item.product.get_url}}"><img src="{{cart_item.product.image.url}}" style="width:100px;height:100px;" alt=""
                                        class="float-left rounded custom_image"></a>
                    </td>
                    <td class="text-left">
                        {{cart_item.product.name}}
                        <br>
                        SKU : {{cart_item.product.id}}
                        <br>
                        Price : ₹{{cart_item.product.price}}
                        <br>
                        Qty : {{cart_item.quantity}}

                    </td>
                    <td>
                        ₹{{cart_item.sub_total}}
                    </td>
                    {% if cart_item.quantity < cart_item.product.stock %}
                    <td>
                        <a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom_a"><i
                                class="fa fa-thin fa-circle-plus custom_icon"></i></a>
                        &nbsp;<a href="{% url 'cart:minus_cart' cart_item.product.id %}" class="custom_a"><i class="fa fa-thin fa-circle-minus custom_icon"></i></a>
                        &nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon"><i class="fa fa-regular fa-trash-can custom_icon"></i></a>
                    </td>
                    {% else %}
                    <td>
                        &nbsp;<a href="{% url 'cart:minus_cart' cart_item.product.id %}" class="custom_a"><i class="fa fa-thin fa-circle-minus custom_icon"></i></a>
                        &nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon"><i class="fa fa-regular fa-trash-can custom_icon"></i></a>
                    </td>
                    {% endif %}
                </tr>

                {% endfor %}
                </tbody>

            </table>

        </div>


        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
            <table class="table my_table">
                <thead class="my_thead">
                <tr>
                    <th>
                        Checkout
                    </th>
                </tr>

                </thead>
                <tbody>
                <tr>
                    <td>
                        Please review your product before proceeding with payment
                    </td>
                </tr>
                <tr>
                    <td>
                        Total Amount : <strong>₹{{total}}</strong>
                    </td>
                </tr>

                </tbody>
            </table>
            <div class="mx-auto">
                <a href="/" class="btn btn-danger my_button" style="margin-bottom:300px;">Continue Shoping</a>  <a href="{% url 'cart:payment' %}" class="btn btn-primary my_button" style="margin-bottom:300px;">Make Payment</a>
            </div>

        </div>

    </div>

</div>

{% endif %}
{% endblock %}

ecommerce/shopcartproject/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
{% if category %}
{{category.description|truncatewords:155}}
{% else %}
Welcome to NOUVA Store
{% endif %}
{% endblock %}
{% block title %}
{% if category %}
{{category.name}} - NOUVA Store
{% else %}
See our Latest Collections - NOUVA Store
{% endif %}
{% endblock %}
{% block content %}
{% if category %}
<div>
    <div class="row my_row_class" style="padding-top : 15px;">
        <div class="mx_auto">
            <p><a style="font-size:20px;" href="{% url 'shopapp:allprodcat' %}">Our Product Collections</a></p>
        </div>
    </div>
</div>
{% endif %}
<div class="mx_auto">
    {% if category %}
    <img style=" width: 1113px;height: 550px;margin-left: 20px;" src="{{category.image.url}}" alt="{{category.name}}">
</div>
<br>
<div>
    <h1 class="text-center my_title">{{category.name}}</h1>
    <p class="text-justify">{{category.description}}</p>
</div>
{% else %}
<div>
    <img width="1117px" class="my_image my_image_padding" src="{% static 'img/banner.png' %}"
         alt="Our products">

</div>
<br>
<div>
    <h1 class="text-center my_title">
        Our products Collections
    </h1>
    <p class="text-justify">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus congue risus eu fringilla
        consectetur. Donec
        aliquet sem in felis laoreet dictum. Aliquam erat volutpat. Donec pretium dui vel magna sollicitudin, quis
        imperdiet lacus rhoncus. Aenean eu lobortis nibh. Phasellus rutrum purus vitae faucibus consectetur. Curabitur a
        fringilla elit. Donec sodales fermentum ante at vestibulum. Phasellus sem eros, consequat sit amet justo eget,
        malesuada tincidunt mi.</p>
</div>
{% endif %}

<div class="container">
    <div class="row mx_auto">
        {% for product in products.object_list %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 xol-lg-4" style="margin-bottom:10px;">
            <div class="card text-center" style="min-width:18rem">
                <a href="{{product.get_url}}"><img class="card-img-top" style="height:334px" src="{{product.image.url}}"
                                                   alt="{{product.name}}"></a>
                <div class="card-body">
                    <h4>{{product.name}}</h4>
                    <p>₹{{product.price}}</p>
                </div>
            </div>

        </div>
        {% endfor %}
    </div>
    <div>
        {% if  products.paginator.num_pages > 1 %}


      <hr>
        <div class="text-center">
            {% for pg in products.paginator.page_range %}
            <a href="?page={{pg}}" style="margin-bottom:5px;" class="btn btn-primary btn-sm  {% if products.number == pg %} active {% endif %}">{{pg}}</a>
            {% endfor %}


        </div>
          {% endif %}

    </div>
</div>
{% endblock %}

ecommerce/shopcartproject/templates/footer.html
<div class="footer  navbar-fixed-bottom my_footer">
  <p class="text-center">&copy; NOUVA tech pvt ltd.All rights Reserved </p>
</div>

ecommerce/shopcartproject/templates/header.html
{% load static %}
<header>
    <center style="    background-color: black;">
      <a href="/"> <img src="{% static 'img/logo.png' %}" alt="logoimage" width="150px" height="150px" ></a>

    </center>
</header>

ecommerce/shopcartproject/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                <li class="nav-item">
                    <a class="nav-link" href="/"><i class="fa fa-light fa-house-chimney"></i><b>Home</b></a>
                </li>
                <li class="nav-item dropdown {% if 'shop' in request.path %} active {% endif %}  ">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="fa fa-brands fa-shopify"></i>Shop
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="{% url 'shopapp:allprodcat' %}">All Products</a></li>
                        {% for cat in links %}
                        <li><a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a></li>
                        {% endfor %}

                    </ul>
                </li>
                {% if item_count > 0 %}
                <li class="nav-item">
                    <a class="nav-link " href="{% url 'cart:cart_detail' %}"> <i class="fa  fa-solid fa-cart-shopping"></i>Cart({{item_count}})</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link " href="{% url 'cart:cart_detail' %}"> <i class="fa  fa-solid fa-cart-shopping"></i>Cart</a>
                </li>
                {% endif %}
            </ul>
            <form class="d-flex" action="{% url 'searchapp:searchresult' %}" method="get">
                <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">
                <button class="btn btn-outline-success" type="submit"><i class="fa fa-search"></i></button>
            </form>
        </div>
    </div>
</nav>

ecommerce/shopcartproject/templates/ordersuccess.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
Order
{% endblock %}
{% block title %}
Order Placed
{% endblock %}
{% block content %}
<div class="row" style="margin-bottom:170px;">
    <div class="container">
        <div class="col-md-12 text-center">
            <h1 class="text-center" style="letter-spacing :.02em;font-size:20px;margin-top:100px;"><b>Order Placed Successfully</b></h1>
            <h1 class="text-center" style="letter-spacing :.02em;font-size:20px;"><b>Thankyou</b></h1>
            <a href="/" class="btn btn-primary" style="margin-top:50px;" >Continue shopping</a>
        </div>
    </div>
</div>

{% endblock %}

ecommerce/shopcartproject/templates/payment.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
Payment
{% endblock %}
{% block title %}
Payment
{% endblock %}
{% block content %}
<div class="container mt-5">
    <form action="">
        <div class="row">
            <div class="col-md-6">
                <h2>Enter Delivery details</h2>
                <div>
                    <label for="">Address</label>
                    <input type="text" class="form-control" id="address" name="address">

                    <label for="">Pincode</label>
                    <input type="text" class="form-control" id="pincode" name="pincode">

                    <label for="">Mobile</label>
                    <input type="text" class="form-control" id="mobile" name="mobile">
                    <input type="text" name="userId" id="" value="" hidden>
                </div>
            </div>
            <div class="col-md-4">
                <div class="container mt-5 ml-5 checkout">
                    <h5>Total Amount :₹{{total}}</h5>
                    <hr>
                    <div class="payment" style="margin-bottom:190px;">
                        <label class="radio-inline">
                            <input type="radio" name="payment-method"  value="COD" checked>COD
                        </label>
                        <label class="radio-inline MT-2">
                            <input type="radio" name="payment-method" value="ONLINE">Online Payment
                        </label>
                        <a href="{% url 'cart:ordersuccess' %}" class="btn btn-primary mt-3 float-right" style="margin-bottom: 22px;">Place Order</a>

                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

ecommerce/shopcartproject/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

{{product.description|truncatewords:155}}


{% endblock %}
{% block title %}
{% if category %}
{{product.name}} - NOUVA Store

{% endif %}
{% endblock %}
{% block content %}
<div>
    <div>
        <p><a href="{{product.category.get_url}}">{{product.category}}</a> | {{product.name}}</p>

    </div>
</div>
<br>
<div class="container">
    <div class="row" style="color:#000;text-decoration:none;font-size:18px;">
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
            <div style="min-width:18rem">
                <img style="height:339px" src="{{product.image.url}}" alt="{{product.name}}">
            </div>
        </div>

        <div class="col-12 col-sm-12 col-md-12 col-lg-6">
            <div>
                <h1 style=" letter-spacing : .02em;font-size:35px;text-transform : uppercase;padding-top:15px;padding-bottom:10px">
                    {{product.name}}</h1>
                <p>₹{{product.price}}</p>
                <p class="my_tittle" style="letter-spacing : .02em;font-size : 16px;text-transform : uppercase;">Product
                    Description</p>
                <p style="text-justify;padding-right:20px;">{{product.description}}</p>
                {% if product.stock <= 0 %}
                <p class="text-justify"><b>Out of Stock</b></p>
                {% else %}
                <a class="btn btn-secondary" style="margin-bottom:10px;" href="{% url 'cart:add_cart' product.id %}">Add
                    to Cart</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

ecommerce/shopcartproject/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

We have variety of products.

{% endblock %}
{% block content %}
<div>
    <p style="padding-top:20px;" class="text-center my_search_text">You have searched for :<b>'{{query}}'</b></p>
</div>
<div class="container">
    <div class="row mx_auto">
        {% for product in products %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 xol-lg-4" style="margin-bottom:10px;">
            <div class="card text-center" style="min-width:18rem">
                <a href="{{product.get_url}}"><img class="card-img-top" style="height:334px" src="{{product.image.url}}"
                                                   alt="{{product.name}}"></a>
                <div class="card-body">
                    <h4>{{product.name}}</h4>
                    <p>₹{{product.price}}</p>
                </div>
            </div>
        </div>
        {% empty %}
        <div class="row mx_auto">
            <p style="padding-top:20px;margin-bottom:319px;" class="text-center my_search_text"> No results found </p>
        </div>


        {% endfor %}
    </div>

</div>
{% endblock %}